projects:
  My AppSync App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-south-1
        apiId: 5ur33hdjkneotjxj5lzq6met64
        maxDepth: 2
extensions:
  amplify:
    version: 3
